### ISSUE TITLE
settings dialog is not opening again

### ISSUE THREAD

**Issue by zstanecic** [Andre9642/BrailleExtender#13]
steps to reproduce:
1. go to the nvda menu, and try to open settings dialog from the Braille extender submenu.
expected: settings dialog should open.
current state:
settings dialog is not opening, and the following log message is in the output:
ERROR - unhandled exception (10:09:54.980):
Traceback (most recent call last):
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 1238, in onSettings
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 43, in __init__
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 262, in __init__
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 431, in <lambda>
TypeError: 'NoneType' object is not iterable

usint the latest master with my last merged translation, 
18.01 preview build compiled manually with scons.

**Comment by Andre9642** [comment]
Thanks for your report.
Could you test with the latest commit? Thanks.

**Comment by zstanecic** [comment]
Hi,
Well, settings dialog is opening, but when you try to save the settings the error sound was played, settings are not saved and the dialog is not closing
Braille tables are not shown in the list. 
I mean, in the list of the displays.

Wysłane z aplikacji Poczta dla Windows 10

Od: André-Abush Clause
Wysłano: wtorek, 6 marca 2018 12:38
Do: Andre9642/BrailleExtender
DW: zstanecic; Author
Temat: Re: [Andre9642/BrailleExtender] settings dialog is not opening again(#13)

Thanks for your report.
Could you test with the latest commit? Thanks.
