### ISSUE TITLE
yet another braille extender error

### ISSUE THREAD

**Issue by zstanecic** [Andre9642/BrailleExtender#23]
1. when trying to open the braille tables or general settings, these dialog fails to open with the following log:
ERROR - unhandled exception (13:52:59.400):
Traceback (most recent call last):
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 58, in onGeneralBtn
  File "gui\settingsDialogs.pyc", line 116, in __init__
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 154, in makeSettings
  File "gui\guiHelper.pyc", line 280, in addLabeledControl
  File "gui\guiHelper.pyc", line 158, in __init__
  File "gui\nvdaControls.pyc", line 37, in __init__
TypeError: SpinCtrl(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 9 has unexpected type 'unicode'

**Comment by Andre9642** [comment]
Indeed, I already had this error randomly. Restart NVDA seems fix this issue.
I hope to fix it soon.
Thanks!

**Comment by zstanecic** [comment]
any progres on this?
@andree9642

**Comment by Andre9642** [comment]
I'll try to work on that this weekend. Thanks.

**Comment by zstanecic** [comment]
as i saw,

it is now fixed successfully.

can you merge my translation PR?


17.10.2018 19:26, André-Abush Clause пишет:
