### ISSUE TITLE
NVDA 2019.3/alpha: critical error when contracted output braille table is used

### ISSUE THREAD

**Issue by Andre9642** [Andre9642/BrailleExtender#48]
With a Python 3 version of NVDA, when a contracted output braille table is used, the braille crashes completely with the following error (current stable and dev versions of Braille Extender are affected):

```
Traceback (most recent call last):
  File "scriptHandler.pyc", line 205, in executeScript
  File "globalCommands.pyc", line 2122, in script_braille_dots
  File "brailleInput.pyc", line 263, in input
  File "brailleInput.pyc", line 232, in _reportUntranslated
  File "brailleInput.pyc", line 191, in _translateForReportContractedCell
  File "louis\__init__.pyc", line 254, in backTranslate
OSError: exception: access violation reading 0x00000000
```

Edit: with the stable version, it seems that the bug produces if a contracted table is used in input and output.

**Comment by Andre9642** [comment]
Also the following errors occur when we (re)start NVDA (with a contracted output braille table):

```
Traceback (most recent call last):
  File "core.pyc", line 486, in main
  File "braille.pyc", line 1864, in message
  File "braille.pyc", line 438, in update
  File "louisHelper.pyc", line 65, in translate
  File "louis\__init__.pyc", line 183, in translate
OSError: exception: access violation reading 0x00000000

Traceback (most recent call last):
  File "eventHandler.pyc", line 155, in executeEvent
  File "eventHandler.pyc", line 92, in __init__
  File "eventHandler.pyc", line 100, in next
  File "C:\Users\andre\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 252, in event_gainFocus
    nextHandler()
  File "eventHandler.pyc", line 100, in next
  File "NVDAObjects\behaviors.pyc", line 185, in event_gainFocus
  File "NVDAObjects\__init__.pyc", line 1103, in event_gainFocus
  File "braille.pyc", line 1905, in handleGainFocus
  File "braille.pyc", line 1910, in _doNewObject
  File "braille.pyc", line 1542, in getFocusContextRegions
  File "braille.pyc", line 633, in update
  File "braille.pyc", line 438, in update
  File "louisHelper.pyc", line 65, in translate
  File "louis\__init__.pyc", line 183, in translate
OSError: exception: access violation reading 0x00000000
```
