### ISSUE TITLE
when NVDA is exited or restarted, braille extender uninitializes properly

### ISSUE THREAD

**Issue by zstanecic** [Andre9642/BrailleExtender#61]
Steps to reproduce: simply exit or restart NVDA.
In the log, we read the following:
ERROR - globalPluginHandler.terminate (11:58:56.660) - MainThread (3452):
Error terminating global plugin <globalPlugins.brailleExtender.GlobalPlugin object at 0x06CA1470>
Traceback (most recent call last):
  File "globalPluginHandler.pyc", line 41, in terminate
  File "C:\Users\zvonimir\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\__init__.py", line 1348, in terminate
    dictionaries.removeTmpDict()
  File "C:\Users\zvonimir\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\dictionaries.py", line 129, in removeTmpDict
    path = getPathDict("tmp")
TypeError: getPathDict() missing 1 required positional argument: 'usableIn'
version of the addon: 20.05.31:1c6df09
windows 10 2004, russian, 64 bit.

**Comment by Andre9642** [comment]
Thanks for this. May be fixed by #56 soon. Affects dev versions only.

**Comment by zstanecic** [comment]
fixed, not applicable
