### ISSUE TITLE
when opening settings and arrowing to open some panels, settings are broken

### ISSUE THREAD

**Issue by zstanecic** [Andre9642/BrailleExtender#85]
here is the log:
ERROR - unhandled exception (16:55:12.030) - MainThread (4392):
Traceback (most recent call last):
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 366, in onCategoryChange
    super().onCategoryChange(evt)
  File "gui\settingsDialogs.pyc", line 597, in onCategoryChange
  File "gui\settingsDialogs.pyc", line 579, in _doCategoryChange
  File "gui\settingsDialogs.pyc", line 500, in _getCategoryPanel
  File "gui\settingsDialogs.pyc", line 275, in __init__
  File "gui\settingsDialogs.pyc", line 285, in _buildGui
  File "C:\Users\ninos\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\auto_scroll.py", line 135, in makeSettings
    initial=get_auto_scroll_delay()
  File "gui\guiHelper.pyc", line 295, in addLabeledControl
  File "gui\guiHelper.pyc", line 172, in __init__
  File "gui\nvdaControls.pyc", line 81, in __init__
TypeError: SpinCtrl(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 9 has unexpected type 'str'
INFO - config.ConfigManager.save (16:55:26.290) - MainThread (4392):
Base configuration saved
ERROR - gui.settingsDialogs.__new__ (17:14:30.302) - MainThread (4392):
Opening new settings dialog while instance still exists: <globalPlugins.brailleExtender.settings.AddonSettingsDialog object at 0x07C3FBC0>
also the dialogs are broken in such a way that NVDA just says panel

**Comment by Andre9642** [comment]
Unfortunately I'm still unable to reproduce the issue. :( Are you able to reproduce it with several installation of NVDA (portable version included)?
Also, could you do the following, please:

1. Open the Python Console (NVDA+Control+z).
2. Paste the following line in the edit field then press enter:
  `config.conf["brailleExtender"]["autoScroll"].copy()`
3. Press F6, then CTRL+A, then CTRL+C.
4. Paste the clipboard content in your reply.

Thanks.

**Comment by zstanecic** [comment]
Hi,
The issue is no longer applicable.
I am going to close this.
