### ISSUE TITLE
Auto-advance: Error when startng auto-advance

### ISSUE THREAD

**Issue by devinprater** [Andre9642/BrailleExtender#92]
Hello. Sometimes, when I try to begin auto-advance mode, I get this error:

```
ERROR - stderr (15:16:45.989) - Thread-1159 (792):
Exception in thread Thread-1159:
Traceback (most recent call last):
  File "threading.pyc", line 926, in _bootstrap_inner
  File "C:\Users\Devin\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\auto_scroll.py", line 34, in run
    next_delay = self._next_delay() / 1000
  File "C:\Users\Devin\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\auto_scroll.py", line 26, in _next_delay
    return get_dynamic_auto_scroll_delay()
  File "C:\Users\Devin\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\auto_scroll.py", line 57, in get_dynamic_auto_scroll_delay
    dynamic_delay = int(size_window / display_size * delay)
TypeError: can't multiply sequence by non-int of type 'float'

```

Additionally, when I try to access auto-scroll settings,I get this:

```
ERROR - gui.settingsDialogs.__new__ (15:22:42.577) - MainThread (4528):
Opening new settings dialog while instance still exists: <globalPlugins.brailleExtender.settings.AddonSettingsDialog object at 0x088541C0>
ERROR - unhandled exception (15:22:43.595) - MainThread (4528):
Traceback (most recent call last):
  File "C:\Users\Devin\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\settings.py", line 372, in onCategoryChange
    super().onCategoryChange(evt)
  File "gui\settingsDialogs.pyc", line 597, in onCategoryChange
  File "gui\settingsDialogs.pyc", line 579, in _doCategoryChange
  File "gui\settingsDialogs.pyc", line 500, in _getCategoryPanel
  File "gui\settingsDialogs.pyc", line 275, in __init__
  File "gui\settingsDialogs.pyc", line 285, in _buildGui
  File "C:\Users\Devin\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\auto_scroll.py", line 123, in makeSettings
    initial=get_auto_scroll_delay()
  File "gui\guiHelper.pyc", line 295, in addLabeledControl
  File "gui\guiHelper.pyc", line 172, in __init__
  File "gui\nvdaControls.pyc", line 81, in __init__
TypeError: SpinCtrl(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 9 has unexpected type 'str'
ERROR - unhandled exception (15:22:47.849) - MainThread (4528):

```

Restarting NVDA fixes this issue. Auto-scroll is set to 3400.

**Comment by Andre9642** [comment]
Hi @devinprater ,
Thanks for this report. Sorry for the delay, I didn't have much time these days.
Indeed I already encountered these bugs. Do you have a scenario to reproduce it easily?
What related options do you have enabled? (Adjust the delay to content, Always ignore blank line).
Thanks

**Comment by aaclause** [comment]
Hi @devinprater, Is this problem still occurring for you with the dev builds?
